### ISSUE TITLE
SLS Gallery and Virtual Microscope playbooks don't restart web

### ISSUE THREAD

**Issue by mtbc** [ome/prod-playbooks#276]
`learning.yml` and `sls-gallery.yml` have `omero_web_systemd_start: False` because there was originally an issue that the playbook would not work correctly for a fresh install, perhaps because the web server was started before all configuration and certificates were yet in place.

**Comment by sbesson** [comment]
Looks like I applied the same change in `learning` in c423a647d6205c6562e56f2dd1fe371319c76c40 during a former upgrade. So let's call this done

**Comment by mtbc** [comment]
(Sorry, was off on vacation in the tropics during this! :palm_tree: Just now back last night.)

@jburel: Given my comment in the description, this was tested for both a fresh server install so that comes up happily first time, as well as for updating an existing installation?
