### ISSUE TITLE
"Download the Figure_To_Pdf.py script"  fails when omero_figure_release is 4.4.0

### ISSUE THREAD

**Issue by stephenogg** [ome/prod-playbooks#314]
TASK [Download the Figure_To_Pdf.py script] ********************************************************************
fatal: [206.12.95.221]: FAILED! => {"changed": false, "dest": "/opt/omero/server/OMERO.server/lib/scripts/omero/figure_scripts/Figure_To_Pdf.py", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://raw.githubusercontent.com/ome/omero-figure/v4.4.0./omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py"}

I think this is due to the fact that on PyPi, omero-figure is released at 4.4.0, but in the Github repo, the latest release is 4.3.1.

**Comment by joshmoore** [comment]
Hi @stephenogg. I see an extra `.` after `v4.4.0`.  https://raw.githubusercontent.com/ome/omero-figure/v4.4.0/omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py loads for me.

**Comment by stephenogg** [comment]
Hi @joshmoore -
😳
So embarrassed.
