### ISSUE TITLE
Server Upgrade to 5.6.4

### ISSUE THREAD

**Issue by jburel** [ome/prod-playbooks#345]
- [x] Pub omero  [@jburel ] 2022-04-28
- [x] demo (@sbesson) - 2022-05-02
- [x] training server [@pwalczysko & @dominikl] 2022-05-02
- [ ] learning [???] (Probably over summer)
- [x] nightshade [@pwalczysko, @dominikl, @sbesson @jburel] 2022-05-04

**Comment by sbesson** [comment]
See https://github.com/ome/prod-playbooks/commit/75d07e3e822baa16dbfb4af71534352e3cdc52cc for the `ome-demoserver` upgrade

**Comment by jburel** [comment]
See 83513f1010cdf648cb5fe4c9a09ed1ed9a0eedb0 for nightshade upgrade

**Comment by jburel** [comment]
See https://github.com/ome/prod-playbooks/pull/346 for training servers upgrade

**Comment by sbesson** [comment]
Email sent to Larissa Kennel to find a relevant time to upgrade the learning system
