### ISSUE TITLE
OMERO.server 5.6.5 upgrade

### ISSUE THREAD

**Issue by sbesson** [ome/prod-playbooks#355]
- [x] ome-demoserver [@sbesson]
- [x] learning  [@sbesson]
- [x] training server [@pwalczysko] 
- [x] ome-dundeeomero [@pwalczysko]

**Comment by sbesson** [comment]
The learning and demo servers were upgraded without issues (https://github.com/ome/prod-playbooks/commit/65dc99ec8936c1e5db69ac0f16e31374be3fe4ae).

**Comment by pwalczysko** [comment]
training servers and nightshade upgraded too without issues
